### ISSUE TITLE
Port 80 already in use

### ISSUE THREAD

**Issue by SergiAguilo** [bsc-health-data/beacon-network-unicas#1]
When using `docker compose` I get the following error:
```
Error response from daemon: driver failed programming external connectivity on endpoint bn-proxy (####): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use
```
I've tried to kill the port before running the container, but I fix nothing.
If you remove the nginx container from the `docker-compose.yaml` the docker seems to work but the final frontend does not work.

**Comment by SergiAguilo** [comment]
when changing port 8081 to 80 in the nginx container, I can solve the problem. I need to check if this is my computer problem or general.
Fix:
```
  nginx:
    image: nginx
    container_name: "bn-proxy"
    depends_on:
      - wildfly
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - beacon-network
    ports:
      - '8081:80'
```
